//
// text.c
// blinkt
//
// Copyright (C) 2018 Michael Budiansky. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification, are permitted
// provided that the following conditions are met:
//
// Redistributions of source code must retain the above copyright notice, this list of conditions
// and the following disclaimer.
//
// Redistributions in binary form must reproduce the above copyright notice, this list of conditions
// and the following disclaimer in the documentation and/or other materials provided with the
// distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
// WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

#include <stdio.h>
#include <string.h>

#include "text.h"

void version(void)
{
    printf("blinkt 0.1\n");
}

void usage(void)
{
    printf("blinkt - controls the LEDs on the Blinkt! board for Raspberry Pi.\n"
           "\n"
           "Usage:\n"
           "  blinkt <color>\n"
           "  blinkt rgb <0-255> <0-255> <0-255>\n"
           "  blinkt bright <0-31>\n"
           "  blinkt clear\n"
           "  blinkt delay <milliseconds>\n"
           "\n"
           "  blinkt <select> <color>\n"
           "  blinkt <select> rgb <0-255> <0-255> <0-255>\n"
           "  blinkt <select> bright <0-31>\n"
           "\n"
           "  blinkt <left | right>\n"
           "  blinkt <off | on>\n"
           "  blinkt <hold | show\n"
           "  blinkt rotate <left | right | in | out>\n"
           "\n"
           "  blinkt binary <mask>\n"
           "  blinkt binary off\n"
           "\n"
           "  blinkt state\n"
           "  blinkt help\n"
           "  blinkt version\n"
           "  blinkt license\n"
           "  blinkt man-page\n"
           "\n"
           "Options:\n"
           "  <color>         red coral orange gold yellow lime green aqua blue purple pink white\n"
           "  <select>        binary pattern showing LEDs affected (00000000 to 11111111);\n"
           "                      to identify a specific pixel by number, use p0, p1, p2, etc.\n"
           "  <left | right>  direction for selecting LEDs: left = left-to-right (rightside up)\n"
           "                                                right = right-to-left (upside down)\n"
           "  <off | on>      off = turn off all LEDs, on = turn as they were before\n"
           "  <hold | show>   hold = save commands without changing LEDs, show = change LEDs immediately\n"
           "  <left | right | in | out>   rotate LEDs according to specified pattern\n"
           "  <mask>          number 0-255 to use as binary mask\n");
}

void license(void)
{
    printf("Copyright (C) 2018 Michael Budiansky. All rights reserved.\n"
           "\n"
           "Redistribution and use in source and binary forms, with or without modification, are permitted\n"
           "provided that the following conditions are met:\n"
           "\n"
           "Redistributions of source code must retain the above copyright notice, this list of conditions\n"
           "and the following disclaimer.\n"
           "\n"
           "Redistributions in binary form must reproduce the above copyright notice, this list of conditions\n"
           "and the following disclaimer in the documentation and/or other materials provided with the\n"
           "distribution.\n"
           "\n"
           "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR\n"
           "IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
           "FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR\n"
           "CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
           "DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
           "DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,\n"
           "WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY\n"
           "WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
           "\n"
           "\n"
           "This software uses the WiringPi library <http://wiringpi.com>, which is installed separately and\n"
           "is released under the GNU Lesser Public License version 3.\n"
           "\n");
}

void man_page_source(void)
{
    printf(".TH blinkt 1\n"
           "\n"
           ".SH NAME\n"
           "blinkt \\- controls the LEDs on the Blinkt! board for Raspberry Pi\n"
           "\n"
           ".SH SYNOPSIS\n"
           ".nf\n"
           "\\fBblinkt\\fR [\\fISELECT\\fR] \\fICOLOR\\fR\n"
           "\\fBblinkt\\fR [\\fISELECT\\fR] \\fBrgb\\fR \\fIRED\\fR \\fIGREEN\\fR \\fIBLUE\\fR\n"
           "\\fBblinkt\\fR \\fBbright\\fR \\fIBRIGHTNESS\\fR\n"
           "\\fBblinkt\\fR \\fBclear\\fR\n"
           "\\fBblinkt\\fR \\fBdelay\\fR \\fIMILLISECONDS\\fR\n"
           "\\fBblinkt\\fR (\\fBleft\\fR | \\fBright\\fR)\n"
           "\\fBblinkt\\fR (\\fBoff\\fR | \\fBon\\fR)\n"
           "\\fBblinkt\\fR (\\fBhold\\fR | \\fBshow\\fR)\n"
           "\\fBblinkt\\fR \\fBrotate\\fR (\\fBleft\\fR | \\fBright\\fR | \\fBin\\fR | \\fBout\\fR)\n"
           "\\fBblinkt\\fR \\fBbinary\\fR (\\fBoff\\fR | \\fIMASK\\fR)\n"
           "\\fBblinkt\\fR \\fBstate\\fR\n"
           "\\fBblinkt\\fR (\\fBhelp\\fR | \\fBversion\\fR | \\fBlicense\\fR | \\fBman\\-page\\fR)\n"
           ".fi\n"
           "\n"
           ".SH DESCRIPTION\n"
           "This tool controls the LEDs on the Blinkt! add\\-on board for the Raspberry Pi. The board has eight\n"
           "pixels, each of which is a combined red, green, and blue LED. The light from each pixel is\n"
           "determined by the separate red, green, and blue intensities from 0 to 255, combined with an overall\n"
           "brightness setting for each pixel from 0 to 31.\n"
           "\n"
           "The blinkt tool also allows RGB values to be specified by one of 12 predefined color names. The\n"
           "color names are approximate; actual appearance may vary according to the brightness and\n"
           "individual variations in boards and LEDs.\n"
           "\n"
           ".SH OPTIONS\n"
           "\n"
           ".TP\n"
           ".BR \\fICOLOR\\fR\n"
           "One of: red coral orange gold yellow lime green aqua blue purple pink white.\n"
           "\n"
           ".TP\n"
           ".BR \\fISELECT\\fR\n"
           "Binary pattern showing LEDs affected (00000000 to 11111111). To identify a specific\n"
           "pixel by number, use p0, p1, p2, etc. Default is all LEDs (11111111).\n"
           "\n"
           ".TP\n"
           ".BR rgb\n"
           "Set color by specifying separate red, green, and blue LED intensities.\n"
           "\n"
           ".TP\n"
           ".BR \\fIRED\\fR\n"
           "Red LED intensity, 0-255. Default is 0.\n"
           "\n"
           ".TP\n"
           ".BR \\fIGREEN\\fR\n"
           "Green LED intensity, 0-255. Default is 0.\n"
           "\n"
           ".TP\n"
           ".BR \\fIBLUE\\fR\n"
           "Blue LED intensity, 0-255. Default is 0.\n"
           "\n"
           ".TP\n"
           ".BR bright\n"
           "Set brightness factor.\n"
           "\n"
           ".TP\n"
           ".BR \\fIBRIGHTNESS\\fR\n"
           "Brightness factor, 0-31. Default is 7.\n"
           "\n"
           ".TP\n"
           ".BR clear\n"
           "Set RGB to 0 0 0 and brightness to 7 for all LEDs. Turn off holding and binary mode.\n"
           "\n"
           ".TP\n"
           ".BR delay\n"
           "Sleep for specified time.\n"
           "\n"
           ".TP\n"
           ".BR \\fIMILLISECONDS\\fR\n"
           "Number of milliseconds to sleep.\n"
           "\n"
           ".TP\n"
           ".BR left \" | \" right\n"
           "Set numbering orientation for LEDs. If \"Blinkt!\" on circuit board is rightside up, choose left\n"
           "(left\\-to\\-right). If \"Blinkt!\" on circuit board is upside down, choose right (right\\-to\\-left).\n"
           "\n"
           ".TP\n"
           ".BR off \" | \" on\n"
           "Turn all LEDs off, or turn LEDs back on to their previous settings (before they were turned off).\n"
           "\n"
           ".TP\n"
           ".BR hold \" | \" show\n"
           "The \"blinkt hold\" command causes changes made by subsequent commands to be saved but not displayed.\n"
           "The \"blinkt show\" command causes all saved commands to be shown, and subsequent commands to be\n"
           "shown immediately.\n"
           "\n"
           ".TP\n"
           ".BR rotate\n"
           "Rotate the pattern of LED colors.\n"
           "\n"
           ".TP\n"
           ".BR left \" | \" right \" | \" in \" | \" out\n"
           "Rotation pattern of LEDs.\n"
           "\n"
           ".TP\n"
           ".BR binary\n"
           "Turn LEDs on or off to display a number as a binary pattern.\n"
           "Does not affect color or brightness settings.\n"
           "\n"
           ".TP\n"
           ".BR off \" | \" \\fIMASK\\fR\n"
           "Decimal number (0-255) to display as binary in LEDs. Specify \"off\" to exit binary mode.\n"
           "\n"
           ".TP\n"
           ".BR state\n"
           "Print out state of LEDs.\n"
           "\n"
           ".TP\n"
           ".BR help\n"
           "Show help message.\n"
           "\n"
           ".TP\n"
           ".BR version\n"
           "Show version.\n"
           "\n"
           ".TP\n"
           ".BR license\n"
           "Show software copyright and license.\n"
           "\n"
           ".TP\n"
           ".BR man-page\n"
           "Show source for this man page\n"
           "\n"
           ".SH EXAMPLES\n"
           "Clear LEDs:\n"
           ".PP\n"
           ".nf\n"
           ".RS\n"
           "\\fBblinkt clear\\fR\n"
           ".RE\n"
           ".fi\n"
           ".PP\n"
           "\n"
           "Turn on all LEDs green at brightness 1:\n"
           ".PP\n"
           ".nf\n"
           ".RS\n"
           "\\fBblinkt green\\fR\n"
           "\\fBblinkt bright 1\\fR\n"
           ".RE\n"
           ".fi\n"
           ".PP\n"
           "\n"
           "Turn on left 4 LEDs blue and right 4 LEDs red:\n"
           ".PP\n"
           ".nf\n"
           ".RS\n"
           "\\fBblinkt 11110000 blue\\fR\n"
           "\\fBblinkt 00001111 red\\fR\n"
           ".RE\n"
           ".fi\n"
           ".PP\n"
           "\n"
           "Rotate LED in pink from left to right:\n"
           ".PP\n"
           ".nf\n"
           ".RS\n"
           "\\fBblinkt clear\\fR\n"
           "\\fBblinkt 10000000 pink\\fR\n"
           "\\fBblinkt delay 200\\fR\n"
           "\\fBblinkt rotate right\\fR\n"
           "\\fBblinkt delay 200\\fR\n"
           "\\fBblinkt rotate right\\fR\n"
           "\\fBblinkt delay 200\\fR\n"
           "\\fBblinkt rotate right\\fR\n"
           "\\fBblinkt delay 200\\fR\n"
           "\\fBblinkt rotate right\\fR\n"
           "\\fBblinkt delay 200\\fR\n"
           "\\fBblinkt rotate right\\fR\n"
           "\\fBblinkt delay 200\\fR\n"
           "\\fBblinkt rotate right\\fR\n"
           "\\fBblinkt delay 200\\fR\n"
           "\\fBblinkt rotate right\\fR\n"
           "\\fBblinkt delay 200\\fR\n"
           "\\fBblinkt clear\\fR\n"
           ".RE\n"
           ".fi\n"
           ".PP\n"
           "\n"
           "Count in binary from 1 to 7:\n"
           ".PP\n"
           ".nf\n"
           ".RS\n"
           "\\fBblinkt clear\\fR\n"
           "\\fBblinkt binary 1\\fR\n"
           "\\fBblinkt yellow\\fR\n"
           "\\fBblinkt delay 700\\fR\n"
           "\\fBblinkt binary 2\\fR\n"
           "\\fBblinkt delay 700\\fR\n"
           "\\fBblinkt binary 3\\fR\n"
           "\\fBblinkt delay 700\\fR\n"
           "\\fBblinkt binary 4\\fR\n"
           "\\fBblinkt delay 700\\fR\n"
           "\\fBblinkt binary 5\\fR\n"
           "\\fBblinkt delay 700\\fR\n"
           "\\fBblinkt binary 6\\fR\n"
           "\\fBblinkt delay 700\\fR\n"
           "\\fBblinkt binary 7\\fR\n"
           "\\fBblinkt delay 700\\fR\n"
           "\\fBblinkt clear\\fR\n"
           ".RE\n"
           ".fi\n"
           ".PP\n"
           "\n"
           ".SH NOTES\n"
           "The Blinkt! board is manufactured by Pimoroni in the UK\n"
           "<\\fIhttps://shop.pimoroni.com/products/blinkt\\fR>.\n"
           "Available in the US from Adafruit <\\fIhttps://www.adafruit.com/product/3195\\fR>.\n"
           "\n"
           "After each invocation of the tool, the LED state is saved in the file \\fI~/.blinkt\\fR\n"
           "\n"
           "To use number bases other than the default, preceed numbers by b for binary, d for\n"
           "decimal, x for hexadecimal. To use a number corresponding to a specific pixel, use\n"
           "p0, p1, p2, etc.\n"
           "\n"
           ".SH AUTHOR\n"
           "Michael Budiansky \\fIhttps://www.7402.org/email\\fR\n");
}
